apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Cambia 2.1.0 por 2.19.1 (o la última versión)
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
  - awx-demo.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1  # Actualiza también aquí

namespace: awx
